In [1]:
import os

import numpy as np
import pandas as pd

# Leaf area

# 2020 Summer

In [2]:
DIRECTORY = './data/2020_S/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [3]:
dates = ['0324', '0421', '0522', '0617', '0707', '0708', '0709']

In [4]:
leaf_area_df = {}
_ = 0
for FILENAME in dataset_list[-1:]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        leaf_area_df[key] = [temp_df[key]['leaf area'][0]]
    _ += 1 
leaf_area_df = pd.DataFrame.from_dict(leaf_area_df).T
leaf_area_df.columns = ['leaf area']

In [5]:
leaf_areas = []
for _ in range(4):
    leaf_areas.append(leaf_area_df.filter(like=dates[_], axis=0).values.T.squeeze())

In [6]:
leaf_area_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        leaf_area_df[key + '_' + dates[-3:][_]] = [temp_df[key]['leaf area'][0]]
    _ += 1 
leaf_area_df = pd.DataFrame.from_dict(leaf_area_df).T
leaf_area_df.columns = ['leaf area']

In [7]:
a2_df = leaf_area_df.filter(like='A2', axis=0)

In [8]:
for _ in range(3):
    leaf_areas.append(a2_df.filter(like=dates[-3:][_], axis=0).values.T.squeeze())

In [9]:
leaf_area_df = pd.DataFrame(leaf_areas, index=['2020-03-24', '2020-04-21', '2020-05-22', '2020-06-17', '2020-07-07', '2020-07-08', '2020-07-09'])

In [10]:
leaf_area_df.index = pd.DatetimeIndex(leaf_area_df.index)

In [11]:
leaf_area_df.to_csv('./results/2020_S/leaf_area.csv')

# 2020 Winter

In [12]:
DIRECTORY = './data/2020_W/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [13]:
leaf_area_df = {}
_ = 0
for FILENAME in dataset_list:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        leaf_area_df[key] = [temp_df[key]['leaf area'][0]]
    _ += 1 
leaf_area_df = pd.DataFrame.from_dict(leaf_area_df).T
leaf_area_df.columns = ['leaf area']

In [14]:
leaf_area_df.index = ['2020-09-09']*3 + ['2020-10-14']*6 + ['2020-11-13']*6 + ['2020-12-11_']*3 + ['2020-12-11']*3

In [15]:
leaf_area_rb_df = leaf_area_df.loc['2020-12-11_']
leaf_area_df = leaf_area_df.drop(['2020-12-11_'])

In [16]:
leaf_areas = []
for _ in range(4):
    leaf_areas.append(leaf_area_df.filter(like=leaf_area_df.index.unique()[_], axis=0).values.T.squeeze())

In [17]:
leaf_areas

[array([870.07, 721.97, 476.31]),
 array([5829.28, 6175.63, 5709.06, 6559.59, 6941.01, 6651.47]),
 array([nan, nan, nan, nan, nan, nan]),
 array([nan, nan, nan])]

In [18]:
leaf_area_df = pd.DataFrame(leaf_areas, index=['2020-09-09', '2020-10-14', '2020-11-13', '2020-12-11'])
leaf_area_df.index = pd.DatetimeIndex(leaf_area_df.index)

In [19]:
leaf_area_df.to_csv('./results/2020_W/leaf_area.csv')

# Plant heights & num nodes

# 2020 Summer

In [20]:
DIRECTORY = './data/2020_S/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [21]:
dates = ['0324', '0421', '0522', '0617', '0707', '0708', '0709']

In [22]:
plant_height_df = {}
num_nodes_df = {}
for FILENAME in dataset_list[-1:]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=1)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
        temp_target = temp_df[key].loc[:, 'stem length(cm)':'stem diameter(mm).1'].dropna(axis=0, how='all')
        temp_target.loc[:, 'stem length(cm).1'] = temp_target['stem length(cm).1'].combine_first(temp_target['stem length(cm)'])
        temp_target.loc[:, 'stem diameter(mm).1'] = temp_target['stem diameter(mm).1'].combine_first(temp_target['stem diameter(mm)'])
        
        plant_height_df[key] = max(temp_target.iloc[:, :2].sum())
        num_nodes_df[key] = temp_target.shape[0]
plant_height_df = pd.DataFrame.from_dict([plant_height_df]).T
plant_height_df.columns = ['plant_height']
num_nodes_df = pd.DataFrame.from_dict([num_nodes_df]).T
num_nodes_df.columns = ['num_nodes_df']

In [23]:
plant_height = []
for _ in range(4):
    plant_height.append(plant_height_df.filter(like=dates[_], axis=0).values.T.squeeze())
num_nodes = []
for _ in range(4):
    num_nodes.append(num_nodes_df.filter(like=dates[_], axis=0).values.T.squeeze())

In [24]:
plant_height_df = {}
num_nodes_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=1)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
        temp_target = temp_df[key].loc[:, 'internode length':'Unnamed: 12'].dropna(axis=0, how='all')
        try:
            temp_target.loc[:, 'internode length.1'] = temp_target['internode length.1'].combine_first(temp_target['internode length'])
        except KeyError:
            temp_target.loc[:, 'Unnamed: 10'] = temp_target['Unnamed: 10'].combine_first(temp_target['internode length'])
        temp_target.loc[:, 'Unnamed: 12'] = temp_target['Unnamed: 12'].combine_first(temp_target['internode diameter'])
        
        plant_height_df[key + '_' + dates[-3:][_]] = max(temp_target.iloc[:, :2].sum())
        num_nodes_df[key + '_' + dates[-3:][_]] = temp_target.shape[0]
    _ += 1
plant_height_df = pd.DataFrame.from_dict([plant_height_df]).T
plant_height_df.columns = ['plant_height']
num_nodes_df = pd.DataFrame.from_dict([num_nodes_df]).T
num_nodes_df.columns = ['num_nodes_df']

In [25]:
a2_df = plant_height_df.filter(like='A2', axis=0)
a2_df_ = num_nodes_df.filter(like='A2', axis=0)

In [26]:
for _ in range(3):
    plant_height.append(a2_df.filter(like=dates[-3:][_], axis=0).values.T.squeeze())
    num_nodes.append(a2_df_.filter(like=dates[-3:][_], axis=0).values.T.squeeze())

In [27]:
plant_height

[array([51.1, 60.6, 45.7]),
 array([141.4, 129.6, 204.2]),
 array([187.8, 158.3, 198.4]),
 array([201.2, 191.8, 210.1, 217.9]),
 array([202. , 200.1, 200.3, 212.8]),
 array([210.1, 210.2, 193.8, 199.8]),
 array([194.5, 192.3, 196.4, 198.2, 192.7, 209.4, 205.6, 187. , 210. ,
        203.5, 180.9, 194.6])]

In [28]:
num_nodes

[array([14, 15, 14]),
 array([21, 23, 21]),
 array([29, 27, 30]),
 array([31, 33, 31, 30]),
 array([31, 31, 27, 32]),
 array([28, 30, 31, 32]),
 array([29, 30, 31, 31, 32, 31, 34, 32, 35, 32, 40, 34])]

In [29]:
plant_height_df = pd.DataFrame(plant_height, index=['2020-03-24', '2020-04-21', '2020-05-22', '2020-06-17', '2020-07-07', '2020-07-08', '2020-07-09'])
num_nodes_df = pd.DataFrame(num_nodes, index=['2020-03-24', '2020-04-21', '2020-05-22', '2020-06-17', '2020-07-07', '2020-07-08', '2020-07-09'])

In [30]:
plant_height_df.index = pd.DatetimeIndex(plant_height_df.index)
num_nodes_df.index = pd.DatetimeIndex(num_nodes_df.index)

In [31]:
plant_height_df.to_csv('./results/2020_S/plant_height.csv')
num_nodes_df.to_csv('./results/2020_S/num_nodes.csv')

# 2020 Winter

In [32]:
DIRECTORY = './data/2020_W/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [33]:
plant_height_df = {}
num_nodes_df = {}
for FILENAME in dataset_list:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=1)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
        temp_target = temp_df[key].loc[:, 'internode length':'internode diameter.1'].dropna(axis=0, how='all')
        temp_target.loc[:, 'internode length.1'] = temp_target['internode length.1'].combine_first(temp_target['internode length'])
        temp_target.loc[:, 'internode diameter.1'] = temp_target['internode diameter.1'].combine_first(temp_target['internode diameter'])
        
        plant_height_df[key] = max(temp_target.iloc[:, :2].sum())
        num_nodes_df[key] = temp_target.shape[0]
plant_height_df = pd.DataFrame.from_dict([plant_height_df]).T
plant_height_df.columns = ['plant_height']
num_nodes_df = pd.DataFrame.from_dict([num_nodes_df]).T
num_nodes_df.columns = ['num_nodes_df']

In [34]:
plant_height_df.index = ['2020-09-09']*3 + ['2020-10-14']*6 + ['2020-11-13']*6 + ['2020-12-11_']*3 + ['2020-12-11']*3
num_nodes_df.index = ['2020-09-09']*3 + ['2020-10-14']*6 + ['2020-11-13']*6 + ['2020-12-11_']*3 + ['2020-12-11']*3
plant_height_rb_df = plant_height_df.loc['2020-12-11_']
plant_height_df = plant_height_df.drop(['2020-12-11_'])
num_nodes_rb_df = num_nodes_df.loc['2020-12-11_']
num_nodes_df = num_nodes_df.drop(['2020-12-11_'])

In [35]:
plant_height = []
num_nodes = []
for _ in range(4):
    plant_height.append(plant_height_df.filter(like=plant_height_df.index.unique()[_], axis=0).values.T.squeeze())
    num_nodes.append(num_nodes_df.filter(like=num_nodes_df.index.unique()[_], axis=0).values.T.squeeze())

In [36]:
plant_height

[array([33.532, 34.782, 28.16 ]),
 array([106.556, 106.89 , 108.362, 128.896, 123.065, 102.295]),
 array([171.393, 185.652, 174.543, 151.061, 163.412, 151.657]),
 array([217.424, 201.218, 216.477])]

In [37]:
num_nodes

[array([ 9, 11, 10]),
 array([19, 20, 20, 21, 21, 22]),
 array([27, 27, 26, 28, 27, 28]),
 array([30, 30, 30])]

In [38]:
plant_height_df = pd.DataFrame(plant_height, index=['2020-09-09', '2020-10-14', '2020-11-13', '2020-12-11'])
num_nodes_df = pd.DataFrame(num_nodes, index=['2020-09-09', '2020-10-14', '2020-11-13', '2020-12-11'])

In [39]:
plant_height_df.index = pd.DatetimeIndex(plant_height_df.index)
num_nodes_df.index = pd.DatetimeIndex(num_nodes_df.index)

In [40]:
plant_height_df.to_csv('./results/2020_W/plant_height.csv')
num_nodes_df.to_csv('./results/2020_W/num_nodes.csv')

# Weights

# 2020 Summer

# Control

In [41]:
DIRECTORY = './data/2020_S/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [42]:
dataset_list

['destructive(0707)_.xlsx',
 'destructive(0708).xlsx',
 'destructive(0709).xlsx',
 'destructive_CT_(0324-0421-0519-0617).xlsx']

In [43]:
FW_df = {}
_ = 0
for FILENAME in dataset_list[-1:]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        FW_df[key] = temp_df[key][['Stem FW', 'Leaf FW', 'petiole FW', 'Fruit count', 'Idv fruit FW', 'Plant height']].iloc[:10, :].sum()
    _ += 1 
FW_df = pd.DataFrame.from_dict(FW_df).T

In [44]:
FW_df.index = ['2020-03-24']*3 + ['2020-04-21']*3 + ['2020-05-22']*3 + ['2020-06-17']*4
__ = FW_df

In [45]:
FW_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        FW_df[key] = temp_df[key][['Stem FW', 'Leaf FW', 'petiole FW', 'Fruit count', 'Idv fruit FW', 'Plant height']].iloc[:10, :].sum()
    _ += 1 
FW_df = pd.DataFrame.from_dict(FW_df).T

In [46]:
FW_df = FW_df.filter(like='A2', axis=0)
FW_df.index = ['2020-07-07' for i in range(len(FW_df.index))]

In [47]:
FW_df = pd.concat([__, FW_df], axis=0, sort=False)

### Dry weights

In [48]:
DW_df = {}
_ = 0
for FILENAME in dataset_list[-1:]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=22)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        DW_df[key] = temp_df[key][['Stem DW', 'Leaf DW', 'petiole DW', 'Fruit DW']].iloc[:3, :].sum()
    _ += 1 
DW_df = pd.DataFrame.from_dict(DW_df).T

In [49]:
DW_df.index = ['2020-03-24']*3 + ['2020-04-21']*3 + ['2020-05-22']*3 + ['2020-06-17']*4
__ = DW_df

In [50]:
DW_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=22)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        DW_df[key] = temp_df[key][['Stem DW', 'Leaf DW', 'petiole DW', 'Fruit DW']].iloc[:3, :].sum()
    _ += 1 
DW_df = pd.DataFrame.from_dict(DW_df).T

In [51]:
DW_df = DW_df.filter(like='A2', axis=0)
DW_df.index = ['2020-07-07' for i in range(len(DW_df.index))]

In [52]:
DW_df = pd.concat([__, DW_df], axis=0, sort=False)

In [53]:
weight_df = pd.concat([FW_df, DW_df], axis=1, sort=False)

In [54]:
weight_df.to_csv('./results/weight_ct.csv')

# 2020 Winter

# Far-red

In [55]:
DIRECTORY = './data/2020_S/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [56]:
dataset_list

['destructive(0707)_.xlsx',
 'destructive(0708).xlsx',
 'destructive(0709).xlsx',
 'destructive_CT_(0324-0421-0519-0617).xlsx']

In [57]:
FW_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        FW_df[key] = temp_df[key][['Stem FW', 'Leaf FW', 'petiole FW', 'Fruit count', 'Idv fruit FW', 'Plant height']].iloc[:10, :].sum()
    _ += 1 
FW_df = pd.DataFrame.from_dict(FW_df).T

In [58]:
FW_df = FW_df.filter(like='A3', axis=0)
FW_df.index = ['2020-07-07' for i in range(len(FW_df.index))]

### Dry weights

In [59]:
DW_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=22)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        DW_df[key] = temp_df[key][['Stem DW', 'Leaf DW', 'petiole DW', 'Fruit DW']].iloc[:3, :].sum()
    _ += 1 
DW_df = pd.DataFrame.from_dict(DW_df).T

In [60]:
DW_df = DW_df.filter(like='A3', axis=0)
DW_df.index = ['2020-07-07' for i in range(len(DW_df.index))]

In [62]:
weight_df = pd.concat([FW_df, DW_df], axis=1, sort=False)

In [64]:
weight_df.to_csv('./results/2020_S/weight_fr.csv')

# interlighting

# 2020 Winter Fresh weights

In [ ]:
DIRECTORY = './data/2020_W/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [ ]:
dataset_list

In [ ]:
FW_df = {}
_ = 0
for FILENAME in dataset_list:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        FW_df[key] = temp_df[key][['Stem FW', 'Leaf FW', 'petiole FW', 'Fruit count', 'Idv fruit FW', 'Plant height']].iloc[:10, :].sum()
    _ += 1 
FW_df = pd.DataFrame.from_dict(FW_df).T

In [ ]:
FW_df.index = ['2020-09-09']*3 + ['2020-10-14']*6 + ['2020-11-13']*6 + ['2020-12-11_']*3 + ['2020-12-11']*3
__ = FW_df

In [ ]:
__rb = __.loc['2020-12-11_']
__rb.index = ['2020-12-11']*3
__ = __.drop('2020-12-11_')

### Dry weights

In [ ]:
DW_df = {}
_ = 0
for FILENAME in dataset_list:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=22)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        DW_df[key] = temp_df[key][['Stem DW', 'Leaf DW', 'petiole DW', 'Fruit DW']].iloc[:3, :].sum()
    _ += 1 
DW_df = pd.DataFrame.from_dict(DW_df).T

In [ ]:
DW_df.index = ['2020-09-09']*3 + ['2020-10-14']*6 + ['2020-11-13']*6 + ['2020-12-11_']*3 + ['2020-12-11']*3

In [ ]:
DW_rb_df = DW_df.loc['2020-12-11_']
DW_rb_df.index = ['2020-12-11']*3
DW_df = DW_df.drop('2020-12-11_')

In [ ]:
weight_ct_df = pd.concat([__, DW_df], axis=1, sort=False)
weight_rb_df = pd.concat([__rb, DW_rb_df], axis=1, sort=False)

In [ ]:
weight_ct_df.to_csv('./results/2020_W/ct_weight.csv')
weight_rb_df.to_csv('./results/2020_W/rb_weight.csv')