In [1]:
import os

import numpy as np
import pandas as pd

## Leaf area

In [2]:
DIRECTORY = './data/destructive/'
file_list = os.listdir(DIRECTORY)
dataset_list = [file for file in file_list if file.endswith('.xlsx')]
dataset_list.sort()

In [3]:
dataset_list

['destructive(0707)_.xlsx',
 'destructive(0708).xlsx',
 'destructive(0709).xlsx',
 'destructive_CT_(0324-0421-0519-0617).xlsx']

In [4]:
dates = ['0324', '0421', '0522', '0617', '0707', '0708', '0709']

In [5]:
leaf_area_df = {}
_ = 0
for FILENAME in dataset_list[-1:]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        leaf_area_df[key] = [temp_df[key]['leaf area'][0]]
    _ += 1 
leaf_area_df = pd.DataFrame.from_dict(leaf_area_df).T
leaf_area_df.columns = ['leaf area']

In [6]:
leaf_areas = []
for _ in range(4):
    leaf_areas.append(leaf_area_df.filter(like=dates[_], axis=0).values.T.squeeze())

In [7]:
leaf_area_df = {}
_ = 0
for FILENAME in dataset_list[:-1]:
    temp_df = pd.read_excel(DIRECTORY + FILENAME, sheet_name=None, skiprows=0)
    for key in temp_df.keys():
        if temp_df[key].shape[0] == 0:
            continue
            
        leaf_area_df[key + '_' + dates[-3:][_]] = [temp_df[key]['leaf area'][0]]
    _ += 1 
leaf_area_df = pd.DataFrame.from_dict(leaf_area_df).T
leaf_area_df.columns = ['leaf area']

In [8]:
a2_df = leaf_area_df.filter(like='A2', axis=0)

In [9]:
for _ in range(3):
    leaf_areas.append(a2_df.filter(like=dates[-3:][_], axis=0).values.T.squeeze())

In [10]:
leaf_areas

[array([2325.75, 2092.14, 1985.18]),
 array([6509.44, 7532.32, 7921.03]),
 array([13240.01, 12620.14, 12134.31]),
 array([15868.04, 14475.55, 14939.53, 15342.76]),
 array([12486.48, 13846.95, 10403.26, 13759.14]),
 array([12861.22, 14610.9 , 10982.65, 12148.78]),
 array([12561.03, 12434.55, 12578.86, 11510.6 , 11054.96, 11971.82,
        11572.67, 11239.36, 13373.94, 11673.69, 11836.51, 12920.71])]

In [11]:
leaf_area_df = pd.DataFrame(leaf_areas, index=['2020-03-24', '2020-04-21', '2020-05-22', '2020-06-17', '2020-07-07', '2020-07-08', '2020-07-09'])

In [12]:
leaf_area_df.index = pd.DatetimeIndex(leaf_area_df.index)

In [13]:
leaf_area_df.to_csv('./results/leaf_area.csv')